### ISSUE TITLE
Add parse_directory

### ISSUE THREAD

**Issue by sami-m-g** [sami-m-g/pyecospold#19]

**Comment by cmutel** [comment]
Here is what I used, it is compatible with [our existing extractor](https://github.com/brightway-lca/brightway2-io/blob/main/bw2io/extractors/ecospold1.py#L26).

```python
from typing import List, Union
from pathlib import Path
from lxml import etree

def parse_directory(dir_path: Union[str, Path], schema_path: str, ecospold_lookup: etree.CustomElementClassLookup, valid_suffixes: List[str] = (".xml", ".spold")
) -> List[etree.ElementBase]: 
    dir_path = Path(dir_path).resolve()
    return [
        es.core.parse_file(file_path=file_path, schema_path=schema_path, ecospold_lookup=ecospold_lookup)
        for file_path in dir_path.iterdir()
        if file_path.is_file() 
        and file_path.suffix.lower() in valid_suffixes
    ]
```

If possible, I would prefer to allow the paths to `parse_x` to also allow for `Path` inputs.

**Comment by sami-m-g** [comment]
09c77fa2dc782bdde89960997bf7d761df596283 added `Path` and `StringIO` as argument types for parse_file functions.

68db0c7838dbc258bdde72732aae453f280deb1a added `parse_directory` functionality. I have basically used your code but set the returned value to be a list of tuples of `Path` and `EcoSpold` for utility purposes.
