### ISSUE TITLE
Manage `TimePeriod` insanity by standardizing to `startDate` and `endDate` only

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#27]
Instead of supporting `startYear`, `startYearMonth`, and `startDate` (who comes up with this stuff?), let's convert on reading to `startDate`, and the same for `endFoo`, and then support easy writing of `fooDate`, which is right now a read-only attribute of `TimePeriod` (i.e. to the pyecospold user `fooDate` should be attributes, not elements.

**Comment by sami-m-g** [comment]
@cmutel we can definitely create a new method which writes simple elements that are basically a tag with text like this one. However, keeping the most detailed element only will introduce the interesting question of what to fill the missing data: for us when reading an existing element that is a `startYear` and for the user when they are writing and don't know any details other than the year.

**Comment by cmutel** [comment]
@sami-m-g You are correct, but in this case I think it is more of a theoretical objection - the practical use of this data will probably be to use the year ranges in any case (based on my experience). But by storing the most detailed representation we don't lose information, and can always go more general if needed.

BTW, I am proposing simplifying the existing implementation, not just adding a new method, so that on reading we convert to `fooDate`, and on writing we always write `fooDate`. I am completely comfortable breaking two-way compatibility in this case, we desperately need to make this format as accessible as possible to less technically-inclined users.

**Comment by cmutel** [comment]
@sami-m-g I am going to try one more time and then give up :) I would like to only have `startDate` and `endDate`, and on reading convert a `Year` or a `YearMonth` to a `Date`. The schema is wrong here, it complex without being powerful.

**Comment by sami-m-g** [comment]
@cmutel - resolved by 2fd461d. Took a bit more time and hatred than expected to develop.
I hope this covers what you need, might be a good idea to refactor in the future.
