### ISSUE TITLE
ecospold v1: Treat `Exchange.inputGroup` and `Exchange.outputGroup` as attribute instead of list of elements

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#28]
The current code follows the schema correctly, and creates `fooGroups` as a list of integers which map to categorical strings. However, this is a poor XSD design decision. I would instead like to make `inputGroup` and `outputGroup` an attribute of our `Exchange` class, with automatic translation when reading and writing. There is always only `fooGroup` element, and it is always *either* `input` or `output`. 

As I am still learning how the automatic data validation works, I don't yet have the skills to implement this; otherwise I would be submitting a PR.

**Comment by sami-m-g** [comment]
@cmutel are we sure we want to break the schema? Similar to #30 this will disable us form reading existing data.

**Comment by sami-m-g** [comment]
@cmutel gentle ping.

**Comment by cmutel** [comment]
Sorry, I think I was unclear with my request. The XML will keep the existing elements, but I would like the `Exchange` class to act as if `inputGroup` or `outputGroup` was an attribute. Both import and export should still work fine, on import just create the class attribute, on export create a new element class right before serialization.

**Comment by sami-m-g** [comment]
Is this so that the value can be changed? Because you can currently do so.
If this is similar to #34, I cna similarly expose a generic attribute called group.

**Comment by cmutel** [comment]
I wasn't thinking of people changing the value, but they should be able to set it when creating new datasets. Yes, exactly like #34, we want a nicer API which still uses the provided schema under the hood.

**Comment by sami-m-g** [comment]
Resolved by 7990f80.
