### ISSUE TITLE
Check CAS number validity on export

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#30]
After #29 is merged, we should use it when someone sets `Exchange.CASNumber` and `ReferenceFunction.CASNumber` in v1, and `casNumber` in the exchange classes in v2.

**Comment by sami-m-g** [comment]
@cmutel - 9aa12d3f38239d5cf982c8a29f46b6a6bf0406d1 completes this, however; it seems that the schema set the size or `CASNumber` to be **11**. We need to either change the schema -and all sample data- to set size to 12, basically breaking it or change our validation to set size to 11.

**Comment by sami-m-g** [comment]
Resolved by #31 and following commits.
