### ISSUE TITLE
Missing inputGroup and outputGroup on IntermediateExchange

### ISSUE THREAD

**Issue by demianruban** [sami-m-g/pyecospold#37]
OS: Linux
Python version: 3.10
Project version: latest

I was using pyecospold to read intermediate exchange in ecoSpold file, but didn't see inputGroup or outputGroup as attributes of IntermediateExchange class, even though there were such child elements of intermediateExchanges in the ecoSpold file.

ElementaryExchange seems to have inputGroup and outputGroup attributes but not IntermediateExchange:

https://github.com/sami-m-g/pyecospold/blob/main/pyecospold/model_v2.py#L1221

**Comment by sami-m-g** [comment]
@demianruban thanks for raising this up. This is now fixed by a0badf5 in v3.1.0 now available on PyPi as well!
