### ISSUE TITLE
ValueError trying to access missing inputGroup or ouputGroup on intermediateExchange

### ISSUE THREAD

**Issue by demianruban** [sami-m-g/pyecospold#38]
OS: Linux
Python version: 3.10
Project version: 3.1.0

I'm trying to check if intermediate exchange has inputGroup by `intermediate_exchange.inputGroup is not None` and get following:

``` python
ValueError: invalid literal for int() with base 10: ''
```

Since IntermediateExchange can have either inputGroup or outputGroup, but not both, one of the two groups would be missing. For me, using `pyecospold`, the way to check this would be to check that either inputGroup or outputGroup `is not None`. In my opinion, `pyecospold` should handle the absence of the element in this context.

**Comment by sami-m-g** [comment]
@demianruban thanks for raising this.
Generic attributes `group `and `groupStr `has been added in `v3.2.0` through b4fcafd to `ElementaryExchange `and `IntermediateExchange`, now available on PyPi.
