### ISSUE TITLE
`group` needs to preserve `input` or `output`

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#39]
[`group`](https://github.com/sami-m-g/pyecospold/blob/main/pyecospold/model_v2.py#L1212) is awesome, but also sucks, because we need to know whether the value is an input or an output. So I have written the following before:

```python
def get_input_and_output_groups(exc: pyecospold.model_v2.IntermediateExchange) -> dict:
    """pyecospold is a bit too aggressive in trying to help find the right group.
    
    Instead of `exc.group` we need to try the underlying data."""
    try:
        input_group = exc._inputGroup
    except ValueError:
        input_group = None
    try:
        output_group = exc._outputGroup
    except ValueError:
        output_group = None
    return {"inputGroup": input_group, "outputGroup": output_group}  
```

I think it is more sensible to expose `_inputGroup` as `inputGroup`, and return `None` if it is missing (similar for `outputGroup`), but am open to other suggestions.

**Comment by sami-m-g** [comment]
Resolved in `v3.4.2`.
