### ISSUE TITLE
Easier access to first element in list of possible elements

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#40]
In practical terms, the following are places where technically more than one element is possible, but in practice only one element is ever provided, and it would make no logical sense (based on the underlying data) to have more than one element:

* ecospold.activityDataset.activityDescription.geography
* ecospold.activityDataset.activityDescription.geography.shortName
* ecospold.activityDataset.activityDescription.activity
* ecospold.activityDataset.flowData.elementaryExchanges.compartment.compartments
* ecospold.activityDataset.flowData.elementaryExchanges.compartment.subCompartments
* ecospold.activityDataset.flowData.elementaryExchanges.name
* ecospold.activityDataset.flowData.elementaryExchanges.unitName
* ecospold.activityDataset.flowData.intermediateExchanges.name
* ecospold.activityDataset.flowData.intermediateExchanges.unitName
* ecospold.activityDataset.activityDescription.activity
* ecospold.activityDataset.activityDescription.activity.activityName

**Comment by sami-m-g** [comment]
Resolved in `v3..3`.
