### ISSUE TITLE
ecospold1 `source` should be a list not a single instance

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#45]
The [can be more than one `source`](https://github.com/sami-m-g/pyecospold/blob/26a17a9c1ef091db049c59b16a3f9293c24a3fb9/pyecospold/schemas/v1/EcoSpold01Dataset.xsd#L82). Should be `sources` instead.

**Comment by sami-m-g** [comment]
Resolved in 22397fd020e2bc71f72b8f1d4dd16cb0df56cb0a.
