### ISSUE TITLE
`percent` field in `representativeness` is too restrictive

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#46]
The [current numerical pattern is 3.1](https://github.com/sami-m-g/pyecospold/blob/c5736e5d468e5e649928a214ad829d7e6c1ef814/pyecospold/schemas/v1/EcoSpold01MetaInformation.xsd#L441); this is way too restrictive. We should either remove this completely, and just keep the max value, or expand it to 3.4.

BTW, no need to push a new release yet, I will be testing with more real-world data in next 1-2 weeks.

**Comment by msgorgi** [comment]
Resolved in a516b0f1d97d501ebe2e130b179068469332734d.

**Comment by sami-m-g** [comment]
Resolved in a516b0f1d97d501ebe2e130b179068469332734d.
